package com.eip.analysis.output;

import com.eip.common.model.CanonicalIncidentEvent;
import com.eip.common.model.IncidentAnalysisResult;
import com.eip.common.model.ScoredMatch;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Map;

@Component
public class ConfluenceTemplateRenderer {

    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z").withZone(ZoneId.of("Asia/Kuala_Lumpur"));

    public String renderRCA(CanonicalIncidentEvent incident, IncidentAnalysisResult analysis) {
        StringBuilder sb = new StringBuilder();
        
        sb.append(String.format("# RCA: %s - %s\n\n", incident.serviceName(), 
            analysis.summary() != null ? analysis.summary() : "Incident Analysis"));

        // Summary table
        sb.append("| Field | Value |\n|-------|-------|\n");
        sb.append(String.format("| Incident ID | %s |\n", incident.incidentId()));
        sb.append(String.format("| Date | %s |\n", FORMATTER.format(Instant.now())));
        sb.append(String.format("| Severity | %s |\n", analysis.severity() != null ? analysis.severity() : "N/A"));
        sb.append(String.format("| Service | %s |\n", incident.serviceName()));
        sb.append(String.format("| Source | %s |\n", incident.source()));
        sb.append(String.format("| Total Exceptions | %d |\n", incident.totalExceptions()));
        sb.append(String.format("| Unique Types | %d |\n", incident.exceptionTypes() != null ? incident.exceptionTypes().size() : 0));
        sb.append(String.format("| AI Confidence | %d%% |\n", analysis.confidencePercent()));
        sb.append(String.format("| Status | %s |\n\n", analysis.status()));

        // Root Cause
        sb.append("## Root Cause\n\n");
        sb.append(analysis.rootCause() != null ? analysis.rootCause() : "_Unable to determine root cause_").append("\n\n");

        // Evidence - Exception Breakdown
        if (incident.exceptionCounts() != null && !incident.exceptionCounts().isEmpty()) {
            sb.append("## Evidence\n\n");
            sb.append("| Exception | Count | Percentage |\n|-----------|-------|------------|\n");
            for (Map.Entry<String, Integer> entry : incident.exceptionCounts().entrySet()) {
                double pct = incident.errorDistribution() != null ? incident.errorDistribution().getOrDefault(entry.getKey(), 0.0) : 0.0;
                sb.append(String.format("| %s | %d | %.1f%% |\n", entry.getKey(), entry.getValue(), pct));
            }
            sb.append("\n");
        }

        // Business Impact
        if (analysis.businessImpact() != null && !analysis.businessImpact().isEmpty()) {
            sb.append("## Business Impact\n\n");
            analysis.businessImpact().forEach(i -> sb.append("- ").append(i).append("\n"));
            sb.append("\n");
        }

        // Recommended Actions
        if (analysis.recommendations() != null) {
            sb.append("## Resolution\n\n");
            if (analysis.recommendations().immediate() != null && !analysis.recommendations().immediate().isEmpty()) {
                sb.append("### Immediate Actions\n");
                analysis.recommendations().immediate().forEach(a -> sb.append("- ").append(a).append("\n"));
                sb.append("\n");
            }
            if (analysis.recommendations().shortTerm() != null && !analysis.recommendations().shortTerm().isEmpty()) {
                sb.append("### Short-term Fixes\n");
                analysis.recommendations().shortTerm().forEach(a -> sb.append("- ").append(a).append("\n"));
                sb.append("\n");
            }
            if (analysis.recommendations().longTerm() != null && !analysis.recommendations().longTerm().isEmpty()) {
                sb.append("### Long-term Prevention\n");
                analysis.recommendations().longTerm().forEach(a -> sb.append("- ").append(a).append("\n"));
                sb.append("\n");
            }
        }

        // Similar Incidents
        if (analysis.similarIncidents() != null && !analysis.similarIncidents().isEmpty()) {
            sb.append("## Similar Past Incidents\n\n");
            sb.append("| Incident | Score | Service | Root Cause |\n|----------|-------|---------|------------|\n");
            for (ScoredMatch match : analysis.similarIncidents()) {
                sb.append(String.format("| %s | %.0f%% | %s | %s |\n",
                    match.incidentId().toString().substring(0, 8) + "...",
                    match.similarityScore() * 100,
                    match.service(),
                    match.rootCause() != null ? truncate(match.rootCause(), 60) : "N/A"));
            }
            sb.append("\n");
        }

        // Footer
        sb.append("---\n\n");
        sb.append(String.format("*Auto-generated by Engineering Intelligence Platform*  \n"));
        sb.append(String.format("*Model: %s | Analyzed: %s*\n", 
            analysis.llmModel() != null ? analysis.llmModel() : "N/A",
            FORMATTER.format(analysis.analyzedAt() != null ? analysis.analyzedAt() : Instant.now())));

        return sb.toString();
    }

    private String truncate(String s, int max) {
        return s.length() <= max ? s : s.substring(0, max) + "...";
    }
}
