package com.eip.analysis.output;

import com.eip.common.model.CanonicalIncidentEvent;
import com.eip.common.model.IncidentAnalysisResult;
import com.eip.common.model.ScoredMatch;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.*;

@Component
public class JiraTemplateRenderer {

    private final ObjectMapper objectMapper = new ObjectMapper()
        .registerModule(new JavaTimeModule())
        .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
        .enable(SerializationFeature.INDENT_OUTPUT);

    public String renderRCAComment(CanonicalIncidentEvent incident, IncidentAnalysisResult analysis) {
        StringBuilder sb = new StringBuilder();
        sb.append("## \uD83E\uDD16 AI Root Cause Analysis\n\n");
        sb.append(String.format("**Severity:** %s | **Confidence:** %d%%\n\n", 
            analysis.severity() != null ? analysis.severity() : "N/A",
            analysis.confidencePercent()));
        
        sb.append("### Root Cause\n");
        sb.append(analysis.rootCause() != null ? analysis.rootCause() : "Unable to determine root cause").append("\n\n");

        if (analysis.recommendations() != null) {
            sb.append("### Recommended Actions\n");
            if (analysis.recommendations().immediate() != null && !analysis.recommendations().immediate().isEmpty()) {
                sb.append("**Immediate:**\n");
                analysis.recommendations().immediate().forEach(a -> sb.append("- ").append(a).append("\n"));
                sb.append("\n");
            }
            if (analysis.recommendations().shortTerm() != null && !analysis.recommendations().shortTerm().isEmpty()) {
                sb.append("**Short-term:**\n");
                analysis.recommendations().shortTerm().forEach(a -> sb.append("- ").append(a).append("\n"));
                sb.append("\n");
            }
            if (analysis.recommendations().longTerm() != null && !analysis.recommendations().longTerm().isEmpty()) {
                sb.append("**Long-term:**\n");
                analysis.recommendations().longTerm().forEach(a -> sb.append("- ").append(a).append("\n"));
                sb.append("\n");
            }
        }

        if (analysis.similarIncidents() != null && !analysis.similarIncidents().isEmpty()) {
            sb.append("### Similar Past Incidents\n");
            for (ScoredMatch match : analysis.similarIncidents()) {
                sb.append(String.format("- %s (%.0f%% match) - %s\n", 
                    match.service(), match.similarityScore() * 100, 
                    match.rootCause() != null ? match.rootCause() : "No RCA available"));
            }
            sb.append("\n");
        }

        sb.append("---\n");
        sb.append(String.format("*Generated by Engineering Intelligence Platform | Model: %s*\n", 
            analysis.llmModel() != null ? analysis.llmModel() : "N/A"));
        return sb.toString();
    }

    public String renderTicketJson(CanonicalIncidentEvent incident, IncidentAnalysisResult analysis) {
        try {
            Map<String, Object> ticket = new LinkedHashMap<>();
            ticket.put("action", "CREATE_TICKET");
            ticket.put("issueType", "Bug");
            ticket.put("summary", String.format("[AI-RCA] %s - %s", 
                incident.serviceName(), 
                analysis.summary() != null ? analysis.summary() : "Incident Analysis"));
            ticket.put("priority", mapSeverityToPriority(analysis.severity()));
            ticket.put("description", renderRCAComment(incident, analysis));
            ticket.put("labels", List.of("ai-generated", "rca", incident.serviceName().toLowerCase().replace(" ", "-")));
            ticket.put("customFields", Map.of(
                "severity", analysis.severity() != null ? analysis.severity() : "MEDIUM",
                "rootCause", analysis.rootCause() != null ? analysis.rootCause() : "",
                "confidence", analysis.confidencePercent()
            ));
            ticket.put("generatedAt", Instant.now().toString());
            ticket.put("incidentId", incident.incidentId().toString());
            ticket.put("posted", false);
            return objectMapper.writeValueAsString(ticket);
        } catch (Exception e) {
            return "{\"error\": \"" + e.getMessage() + "\"}";
        }
    }

    private String mapSeverityToPriority(String severity) {
        if (severity == null) return "Medium";
        return switch (severity.toUpperCase()) {
            case "CRITICAL" -> "Highest";
            case "HIGH" -> "High";
            case "MEDIUM" -> "Medium";
            case "LOW" -> "Low";
            default -> "Medium";
        };
    }
}
