package com.eip.common.enums;

public enum SimulationScenario {
    DATABASE_UNAVAILABLE,
    SERVICE_TIMEOUT,
    CONNECTION_REFUSED,
    NULL_POINTER_EXCEPTION,
    LATENCY_SPIKE,
    MEMORY_EXHAUSTION,
    THREAD_DEADLOCK,
    AUTHENTICATION_FAILURE,
    DISK_FULL,
    NETWORK_PARTITION
}
